#expected-config.yml
# When you have gitlab.sync.[entity].enabled: true, it means those entities w "synced FROM GitHub" TO GitLab
gitlab:
  enabled: true
  projectId: # recommended, if present, you do not need the following fields
  url: "gitlab.com" # Optional, defaults to gitlab.com
  username: vikshan # Optional, defaults to GitHub repo owner
  repo: devcontainers # Optional, defaults to GitHub repo name
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"

    pullRequests:
      enabled: true
      autoMerge: false
      labels: "synced-from-gitlab"

    issues:
      enabled: true
      syncComments: false
      labels: "synced-from-gitlab"

    releases:
      enabled: true

    tags:
      enabled: true # automatically enabled if releases = true

# When you have github.sync.[entity].enabled: true, it means those entities will be "synced FROM GitLab" TO GitHub
github:
  enabled: true
  username: iamvikshan # Optional, defaults to GitHub username
  repo: devcontainers # Optional, defaults to GitHub repo name
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"

    pullRequests:
      enabled: true
      autoMerge: false
      labels: "synced-from-gitlab"

    issues:
      enabled: true
      syncComments: false
      labels: "synced-from-gitlab"

    releases:
      enabled: true

    tags:
      enabled: true # automatically enabled if releases = true
