#expected-config.yml
# When you have gitlab.sync.[entity].enabled: true, it means those entities will be synced FROM GitHub TO GitLab
gitlab:
  enabled: true
  url: "gitlab.com" # Optional, defaults to gitlab.com
  username: # Optional, defaults to GitHub repo owner
  repo: # Optional, defaults to GitHub repo name
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"

    pullRequests:
      enabled: true
      autoMerge: false
      labels: ["synced-from-github"]

    issues:
      enabled: true
      syncComments: true
      labels: ["synced-from-github"]

    releases:
      enabled: true

    tags:
      enabled: true # automatically enabled if releases = true

# When you have github.sync.[entity].enabled: true, it means those entities will be synced FROM GitLab TO GitHub
github:
  enabled: true
  username: # Optional, defaults to GitHub username
  repo: # Optional, defaults to GitHub repo name
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"

    pullRequests:
      enabled: true
      autoMerge: false
      labels: ["synced-from-gitlab"]

    issues:
      enabled: true
      syncComments: true
      labels: ["synced-from-gitlab"]

    releases:
      enabled: true

    tags:
      enabled: true # automatically enabled if releases = true
