# Example configuration for advanced-git-sync action
# This file demonstrates the correct YAML syntax for all configuration options
#
# IMPORTANT: If your sync includes workflow files (.github/workflows/), you MUST use
# a Personal Access Token with 'workflow' scope as GH_TOKEN secret instead of GITHUB_TOKEN

# GitLab Configuration
# When gitlab.sync.[entity].enabled: true, entities will be synced FROM GitHub TO GitLab
gitlab:
  enabled: true
  owner: your-gitlab-username # Replace with your GitLab username
  repo: your-repo-name # Replace with your repository name (optional if same as GitHub)
  projectId: 12345 # Optional: GitLab project ID (if different from owner/repo)
  sync:
    branches:
      enabled: true
      protected: true # Include protected branches
      pattern: "*" # Pattern to match branch names (* = all branches)
    pullRequests:
      enabled: true
      autoMerge: false # Don't auto-merge synced PRs
      labels: ["synced", "github-origin"] # Labels to add to synced PRs
    issues:
      enabled: true
      syncComments: false # Don't sync issue comments (can be resource intensive)
      labels: ["synced", "github-origin"] # Labels to add to synced issues
    releases:
      enabled: true # Sync releases and their assets
    tags:
      enabled: true # Sync Git tags

# GitHub Configuration
# When github.sync.[entity].enabled: true, entities will be synced FROM GitLab TO GitHub
github:
  enabled: true
  # owner and repo are automatically detected from the GitHub context
  sync:
    branches:
      enabled: true
      protected: true # Include protected branches
      pattern: "*" # Pattern to match branch names
    pullRequests:
      enabled: true
      autoMerge: false # Don't auto-merge synced PRs
      labels: ["synced", "gitlab-origin"] # Labels to add to synced PRs
    issues:
      enabled: true
      syncComments: false # Don't sync issue comments
      labels: ["synced", "gitlab-origin"] # Labels to add to synced issues
    releases:
      enabled: true # Sync releases and their assets
    tags:
      enabled: true # Sync Git tags

# Alternative label configurations:
#
# Single label as string:
# labels: "synced"
#
# Multiple labels as array (recommended):
# labels: ["synced", "automated", "cross-platform"]
#
# No labels:
# labels: []

# Branch pattern examples:
# pattern: "*"           # All branches
# pattern: "main"        # Only main branch
# pattern: "feature/*"   # All feature branches
# pattern: "release/*"   # All release branches

# Performance considerations:
# - Set syncComments: false for better performance
# - Use specific branch patterns instead of "*" if you have many branches
# - Consider disabling releases/tags sync if not needed
# - The action now runs operations in parallel for better performance
